[theme]
base="dark"
primaryColor="#6ee7b7"
backgroundColor="#0f172a"
secondaryBackgroundColor="#111827"
textColor="#e5e7eb"

[server]
enableCORS = true
enableXsrfProtection = true
headless = true

[browser]
gatherUsageStats = false
